Repository hackforla/food-oasis, pull requests merged in 2023-10, with the labels that each got.

#1825 Fix correction form reset
  client/src/components/FoodSeeker/SearchResults/StakeholderDetails/CorrectionDialog.js
Labels: hacktoberfest-accepted

#1829 Use sx props when styling Desktop.js
  client/src/components/FoodSeeker/SearchResults/layouts/Desktop.js
Labels: hacktoberfest-accepted

#1831 SearchCriteriaDisplay makeStyles
  client/src/components/Admin/SearchCriteriaDisplay.js
Labels: hacktoberfest-accepted

#1855 fix type error on validation schema
  server/app/validation-schema/suggestion-schema.ts
  server/app/validation-schema/tag-schema.ts
Labels: Hacktoberfest, hacktoberfest-accepted

#1860 Remove makeStyles from ImportFile
  client/src/components/Admin/ImportOrganizations/ImportFile.js
Labels: Hacktoberfest, hacktoberfest-accepted

#1864 Remove unused colorblock.js
  client/src/components/UI/ColorBlock.js
Labels: hacktoberfest-accepted

#1863 Converted makestyles to sx in ./Mobile.js
  client/src/components/FoodSeeker/SearchResults/layouts/Mobile.js
Labels: hacktoberfest-accepted

#1862 1861-Align Map Search Textinput and Icon
  client/src/components/FoodSeeker/SearchResults/ResultsFilters/ResultsFilters.js
Labels: hacktoberfest-accepted

#1841 Update styling to use sx prop verification admin 1833
  client/src/components/Admin/VerificationAdmin.js
Labels: dev, Role: Front-end, size: 1pt, Feature: Design System, Release Note: System Update, hacktoberfest-accepted, Material-UI v.5, 23s04

#1851 Update styling to use sx prop TagAdmin.js 1832
  client/src/components/Admin/TagAdmin.js
Labels: dev, Role: Front-end, size: 1pt, Feature: Design System, Release Note: System Update, hacktoberfest-accepted, Material-UI v.5, 23s04

#1854 1845 makeStyles SB About.js
  client/src/components/StaticPagesSB/About.js
  client/src/components/StaticPagesSB/assets/IconSpacerSVG.js
  client/src/components/StaticPagesSB/assets/farm2people.png
Labels: hacktoberfest-accepted

#1850 1844 makeStyles MCK About page
  client/src/components/StaticPagesMCK/About.js
  client/src/components/StaticPagesMCK/assets/farm2people.png
Labels: hacktoberfest-accepted

#1843 Removed makeStyles in VerificationDashboard.js
  client/src/components/Admin/VerificationDashboard.js
Labels: hacktoberfest-accepted

#1842 Update styles importDialogue.js
  client/src/components/Admin/ImportOrganizations/ImportDialog.js
Labels: hacktoberfest-accepted

#1866 Updated styles in StaticPagesMCK/Donate.js
  client/src/components/StaticPagesMCK/Donate.js
Labels: hacktoberfest-accepted

#1877 1847 makeStyles MCK FAQ
  client/src/components/StaticPagesMCK/Faq.js
  client/src/components/StaticPagesMCK/assets/IconSpacerSVG.js
Labels: hacktoberfest-accepted

#1878 Updated styling for Importfileguide.js
  client/src/components/Admin/ImportOrganizations/ImportFileGuide.js
Labels: hacktoberfest-accepted

#1879 Update Styling System to Use sx Prop in Material-UI Components in StaticPagesSB/Donate.js
  client/src/components/StaticPagesSB/Donate.js
Labels: hacktoberfest-accepted

#1870 removed unused components and variables
  client/src/components/Admin/TagAdmin.js
  client/src/components/Admin/VerificationAdmin.js
Labels: hacktoberfest-accepted

#1872 removes unused code from client
  client/src/components/Admin/ImportOrganizations/ImportFile.js
  client/src/components/Admin/OrganizationEdit.js
  client/src/components/Admin/SearchCriteria.js
  client/src/components/Admin/Suggestions.js
  client/src/components/Admin/TagAdmin.js
  client/src/components/Admin/VerificationAdmin.js
  client/src/components/FoodSeeker/Home.js
  client/src/components/FoodSeeker/SearchResults/ResultsFilters/ResultsFilters.js
  client/src/components/FoodSeeker/SearchResults/ResultsMap/MarkerHelpers.js
  client/src/components/FoodSeeker/SearchResults/ResultsMap/ResultsMap.js
  client/src/components/FoodSeeker/SearchResults/StakeholderPreview/StakeholderPreview.js
  client/src/components/FoodSeeker/Suggestion.js
  client/src/components/Layout/WidgetFooter.js
  client/src/components/StaticPagesSB/About.js
  client/src/components/StaticPagesSB/Donate.js
  client/src/components/StaticPagesSB/Faq.js
  client/src/theme/overrides/Button.js
  client/src/theme/overrides/Chip.js
  client/src/theme/typography.js
Labels: hacktoberfest-accepted

#1830 #1858 switch search to selectAll endpoint inst of search
  client/src/appReducer.js
  client/src/components/FoodSeeker/SearchResults/SearchResults.js
  client/src/components/FoodSeeker/SearchResults/StakeholderDetails/StakeholderDetails.js
  client/src/helpers/index.js
  client/src/hooks/useOrganizationBests.js
  client/src/services/stakeholder-best-service.js
Labels: hacktoberfest-accepted

#1868 Update search result UI for Mobile
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/FoodSeeker/SearchResults/SearchResults.js
  client/src/components/FoodSeeker/SearchResults/layouts/Mobile.js
Labels: hacktoberfest-accepted

#1886 remove makestyle from SB Faq page
  client/src/components/StaticPagesSB/Faq.js
Labels: hacktoberfest-accepted

#1882 Remove ScaleControl
  client/src/components/FoodSeeker/SearchResults/ResultsMap/ResultsMap.js
Labels: hacktoberfest-accepted

#1883 changed style system in ImportFileTable.js
  client/src/components/Admin/ImportOrganizations/ImportFileTable.js
Labels: hacktoberfest-accepted

#1895 Use the new food pantry icon
  client/src/components/FoodSeeker/SearchResults/StakeholderDetails/StakeholderDetails.js
  client/src/icons/PantryIcon.js
  client/src/images/mapMarker.js
  client/src/images/stakeholderIcon.js
Labels: hacktoberfest-accepted

#1898 1897-Swap SplitPantryMealIcon
  client/src/icons/SplitPantryMealIcon.js
  client/src/images/mapMarker.js
  client/src/images/stakeholderIcon.js
Labels: Hacktoberfest, hacktoberfest-accepted

#1901 Use the new meal icon
  client/src/icons/MealIcon.js
  client/src/icons/PantryIcon.js
  client/src/icons/SplitPantryMealIcon.js
  client/src/images/mapMarker.js
  client/src/images/stakeholderIcon.js
  client/src/theme/palette.js
Labels: hacktoberfest-accepted

#1893 modified mobile list view dragging
  client/package-lock.json
  client/src/components/FoodSeeker/SearchResults/layouts/Mobile.js
  package-lock.json
Labels: hacktoberfest-accepted

#1896 1691 fix search autocomplete disappear bug
  client/src/components/FoodSeeker/AddressDropDown.js
Labels: hacktoberfest-accepted

#1905 minor improvement to code and content
  client/src/components/FoodSeeker/Home.js
  client/src/components/StaticPagesMCK/About.js
Labels: hacktoberfest-accepted
